/*
 *  Trigger for activating procedures based on button click, location, or other user interaction
 *  - generated by claude 3.7
 */

using UnityEngine;
using UnityEngine.UI;

public class ProcedureTrigger : MonoBehaviour
{
    [Header("Procedure Settings")]
    [SerializeField] private string procedureName = "Egress";
    [SerializeField] private ProcedureDisplay procedureDisplay;
    
    [Header("Trigger Type")]
    [SerializeField] private bool triggerOnButtonClick = true;
    [SerializeField] private bool triggerOnLocationEnter = false;
    
    [Header("Button Reference (if using button trigger)")]
    [SerializeField] private Button triggerButton;
    
    [Header("Location Trigger (if using location trigger)")]
    [SerializeField] private string locationTag = "Station";
    [SerializeField] private float triggerRadius = 2.0f;
    
    private bool playerInLocation = false;
    
    //*------ Functions ------*/
    private void Start()
    {       
        if (triggerOnButtonClick && triggerButton != null)
            triggerButton.onClick.AddListener(OnTriggerButtonClicked);
    }
    
    private void OnDestroy()
    {
        if (triggerButton != null)
            triggerButton.onClick.RemoveListener(OnTriggerButtonClicked);
    }
    
    private void Update()
    {
        if (triggerOnLocationEnter) CheckLocationTrigger();
    }
    
    // check if player is in a specific location
    private void CheckLocationTrigger()
    {
        // This is a simple implementation - you might want to use colliders instead
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        
        if (player) {
            // Check if player is in range
            bool inRange = Vector3.Distance(transform.position, player.transform.position) <= triggerRadius;
            
            // Only trigger when player first enters the location
            if (inRange && !playerInLocation)
            {
                playerInLocation = true;
                ActivateProcedure();
            }
            else
                playerInLocation = false;
        }
    }
    
    // activate procedure if button is clicked
    private void OnTriggerButtonClicked()
    {
        ActivateProcedure();
    }
    
    // activate procedure if not already active
    private void ActivateProcedure() {
        if (procedureDisplay != null && !procedureDisplay.IsProcedureActive())
            procedureDisplay.LoadProcedure(procedureName);
    }
    
    // when player leaves station location, set playerInLocation to false
    private void OnTriggerExit(Collider other) {
        if (triggerOnLocationEnter && other.CompareTag("Player"))
            playerInLocation = false;
    }
} 