/*
 *  Trigger for activating procedures based on button click, location, or other user interaction
 *  - generated by claude 3.7
 */

using UnityEngine;
using UnityEngine.UI;

public class ProcedureTrigger : MonoBehaviour
{
    [Header("Procedure Settings")]
    [SerializeField] private string procedureName = "Egress";
    [SerializeField] private ProcedureDisplay procedureDisplay;
    
    [Header("Trigger Type")]
    [SerializeField] private bool triggerOnButtonClick = true;
    [SerializeField] private bool triggerOnLocationEnter = false;
    
    [Header("Button Reference (if using button trigger)")]
    [SerializeField] private Button triggerButton;
    
    [Header("Location Trigger (if using location trigger)")]
    [SerializeField] private string locationTag = "Station";
    [SerializeField] private float triggerRadius = 2.0f;
    
    private bool playerInLocation = false;
    
    private void Start()
    {
        if (procedureDisplay == null)
        {
            Debug.LogError("ProcedureTrigger: ProcedureDisplay reference is missing!");
        }
        
        if (triggerOnButtonClick && triggerButton != null)
        {
            triggerButton.onClick.AddListener(OnTriggerButtonClicked);
        }
    }
    
    private void OnDestroy()
    {
        if (triggerButton != null)
        {
            triggerButton.onClick.RemoveListener(OnTriggerButtonClicked);
        }
    }
    
    private void Update()
    {
        if (triggerOnLocationEnter)
        {
            CheckLocationTrigger();
        }
    }
    
    private void CheckLocationTrigger()
    {
        // This is a simple implementation - you might want to use colliders instead
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        
        if (player != null)
        {
            // Check if player is in range
            bool inRange = Vector3.Distance(transform.position, player.transform.position) <= triggerRadius;
            
            // Only trigger when player first enters the location
            if (inRange && !playerInLocation)
            {
                playerInLocation = true;
                ActivateProcedure();
            }
            else if (!inRange && playerInLocation)
            {
                playerInLocation = false;
            }
        }
    }
    
    private void OnTriggerButtonClicked()
    {
        ActivateProcedure();
    }
    
    private void ActivateProcedure()
    {
        if (procedureDisplay != null && !procedureDisplay.IsProcedureActive())
        {
            procedureDisplay.LoadProcedureByName(procedureName);
        }
    }
    
    // For use with Unity collider triggers if preferred
    private void OnTriggerEnter(Collider other)
    {
        if (triggerOnLocationEnter && other.CompareTag("Player"))
        {
            playerInLocation = true;
            ActivateProcedure();
        }
    }
    
    private void OnTriggerExit(Collider other)
    {
        if (triggerOnLocationEnter && other.CompareTag("Player"))
        {
            playerInLocation = false;
        }
    }
} 